version: '3'
services:
  webserver:
    build:
      dockerfile: Dockerfile
      context: ./
      args:
        GS_ACCESS_KEY_ID: ${GS_ACCESS_KEY_ID} # from .env
        GS_SECRET_ACCESS_KEY: ${GS_SECRET_ACCESS_KEY} #from .env    
    volumes:
      - app-vol:/voldata
    ports:
      - "8088:8088"
volumes:
  app-vol: