name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

    deploy:

        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        container: docker://dvcorg/cml-py3:latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
        steps:
        - name: Login
          uses: google-github-actions/setup-gcloud@v0
          env:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_email: ${{ secrets.GCP_EMAIL }}
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}
            
        - uses: actions/checkout@v2    
        - uses: iterative/setup-dvc@v1
        - name: DVC pull
          run: |
            pip install dvc
            pip install dvc[gs]
            dvc remote modify --local remote_storage credentialpath ${{ secrets.GCP_CREDENTIALS }}
            dvc pull --run-cache
            dvc repro

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME -f trainer.dockerfile --build-arg KEY_FILE_CONTENT=${{ secrets.GCP_CREDENTIALS }}

        - name: Test Docker image
          run: docker run $IMAGE_NAME sh -c "go test -v"

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region us-central1 --platform managed
