name: "model tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-10.15, windows-2019]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: iterative/setup-dvc@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Cache pip
      uses: actions/cache@v2
      id: cache-pip
      with:
        path: ~/.cache/pip
        # The cache key 
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: |
         pip install -r requirements.txt
         pip install -r requirements_tests.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v
