name: "model tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-10.15, windows-2019]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
	
    - name: Cache pip
      uses: actions/cache@v2
      id: cache-pip
      with:
        path: ~/.cache/pip
        # The cache key 
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: |
         pip install -r requirements.txt
         pip install -r requirements_tests.txt
    - name: Test with pytest
      env:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      GS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      GS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
	pip install dvc
	pip install dvc[gs]
	
        pip install pytest

	dvc pull --run-cache
	dvc repro

        pytest -v
